/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malsha
 */
public class CafeScreen extends javax.swing.JFrame {

    /**
     * Creates new form CafeScreen
     */
    public CafeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        drinkPanel = new javax.swing.JPanel();
        nesCafe = new javax.swing.JCheckBox();
        qIceCofee = new javax.swing.JTextField();
        iceCofee = new javax.swing.JCheckBox();
        hotCoffee = new javax.swing.JCheckBox();
        milo = new javax.swing.JCheckBox();
        tea = new javax.swing.JCheckBox();
        nesTea = new javax.swing.JCheckBox();
        qhotcofee = new javax.swing.JTextField();
        qMilo = new javax.swing.JTextField();
        qTea = new javax.swing.JTextField();
        qNesTea = new javax.swing.JTextField();
        qNesCafe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        shortEatspanel = new javax.swing.JPanel();
        doNut = new javax.swing.JCheckBox();
        hotDog = new javax.swing.JCheckBox();
        fishBurger = new javax.swing.JCheckBox();
        cupCake = new javax.swing.JCheckBox();
        cheeseBurger = new javax.swing.JCheckBox();
        chickenBurger = new javax.swing.JCheckBox();
        qCupCake = new javax.swing.JTextField();
        qDoNut = new javax.swing.JTextField();
        qHotDog = new javax.swing.JTextField();
        qCheeseBurger = new javax.swing.JTextField();
        qFishBurger = new javax.swing.JTextField();
        qChickenBurger = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        costOfShortEats = new javax.swing.JLabel();
        costOfDrinks = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalCharge = new javax.swing.JLabel();
        pricecostOfDrinks = new javax.swing.JLabel();
        pcostOfShortEats = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        total = new javax.swing.JButton();
        close = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(java.awt.Color.red);
        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Cafe Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 1420, 110));

        drinkPanel.setBackground(new java.awt.Color(153, 153, 153));
        drinkPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nesCafe.setBackground(new java.awt.Color(153, 153, 153));
        nesCafe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nesCafe.setText("    NesCafe");
        nesCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nesCafeActionPerformed(evt);
            }
        });

        qIceCofee.setBackground(new java.awt.Color(153, 153, 153));
        qIceCofee.setText("               ");
        qIceCofee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iceCofee.setBackground(new java.awt.Color(153, 153, 153));
        iceCofee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iceCofee.setText("    Ice Coffee");
        iceCofee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iceCofeeActionPerformed(evt);
            }
        });

        hotCoffee.setBackground(new java.awt.Color(153, 153, 153));
        hotCoffee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hotCoffee.setText("    Hot Coffee");

        milo.setBackground(new java.awt.Color(153, 153, 153));
        milo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        milo.setText("    Milo");

        tea.setBackground(new java.awt.Color(153, 153, 153));
        tea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tea.setText("    Tea");
        tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaActionPerformed(evt);
            }
        });

        nesTea.setBackground(new java.awt.Color(153, 153, 153));
        nesTea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nesTea.setText("    NesTea ");

        qhotcofee.setBackground(new java.awt.Color(153, 153, 153));
        qhotcofee.setText("         ");
        qhotcofee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qMilo.setBackground(new java.awt.Color(153, 153, 153));
        qMilo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qTea.setBackground(new java.awt.Color(153, 153, 153));
        qTea.setText("        ");
        qTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qNesTea.setBackground(new java.awt.Color(153, 153, 153));
        qNesTea.setText("          ");
        qNesTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qNesCafe.setBackground(new java.awt.Color(153, 153, 153));
        qNesCafe.setText("        ");
        qNesCafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Drinks");

        javax.swing.GroupLayout drinkPanelLayout = new javax.swing.GroupLayout(drinkPanel);
        drinkPanel.setLayout(drinkPanelLayout);
        drinkPanelLayout.setHorizontalGroup(
            drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinkPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hotCoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iceCofee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nesCafe)
                    .addComponent(nesTea)
                    .addComponent(tea)
                    .addComponent(milo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qNesTea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qTea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(qhotcofee, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qIceCofee, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qNesCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qMilo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinkPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        drinkPanelLayout.setVerticalGroup(
            drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinkPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(34, 34, 34)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qIceCofee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iceCofee))
                .addGap(37, 37, 37)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qhotcofee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotCoffee))
                .addGap(38, 38, 38)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qNesCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nesCafe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qNesTea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nesTea))
                .addGap(34, 34, 34)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qTea))
                .addGap(47, 47, 47)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qMilo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milo))
                .addGap(56, 56, 56))
        );

        getContentPane().add(drinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 470, 490));

        shortEatspanel.setBackground(new java.awt.Color(153, 153, 153));
        shortEatspanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        doNut.setBackground(new java.awt.Color(153, 153, 153));
        doNut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doNut.setText("    DoNut");
        doNut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doNutActionPerformed(evt);
            }
        });

        hotDog.setBackground(new java.awt.Color(153, 153, 153));
        hotDog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hotDog.setText("    Hot Dog");
        hotDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotDogActionPerformed(evt);
            }
        });

        fishBurger.setBackground(new java.awt.Color(153, 153, 153));
        fishBurger.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fishBurger.setText("    Fish Burger");
        fishBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishBurgerActionPerformed(evt);
            }
        });

        cupCake.setBackground(new java.awt.Color(153, 153, 153));
        cupCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cupCake.setText("    Cup Cake");
        cupCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupCakeActionPerformed(evt);
            }
        });

        cheeseBurger.setBackground(new java.awt.Color(153, 153, 153));
        cheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cheeseBurger.setText("     Cheese Burger");
        cheeseBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseBurgerActionPerformed(evt);
            }
        });

        chickenBurger.setBackground(new java.awt.Color(153, 153, 153));
        chickenBurger.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chickenBurger.setText("     Chicken Burger");
        chickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenBurgerActionPerformed(evt);
            }
        });

        qCupCake.setBackground(new java.awt.Color(153, 153, 153));
        qCupCake.setText("          ");
        qCupCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qCupCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qCupCakeActionPerformed(evt);
            }
        });

        qDoNut.setBackground(new java.awt.Color(153, 153, 153));
        qDoNut.setText("         ");
        qDoNut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qHotDog.setBackground(new java.awt.Color(153, 153, 153));
        qHotDog.setText("           ");
        qHotDog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qCheeseBurger.setBackground(new java.awt.Color(153, 153, 153));
        qCheeseBurger.setText("       ");
        qCheeseBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qFishBurger.setBackground(new java.awt.Color(153, 153, 153));
        qFishBurger.setText("          ");
        qFishBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qChickenBurger.setBackground(new java.awt.Color(153, 153, 153));
        qChickenBurger.setText("          ");
        qChickenBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("    ShortEats");

        javax.swing.GroupLayout shortEatspanelLayout = new javax.swing.GroupLayout(shortEatspanel);
        shortEatspanel.setLayout(shortEatspanelLayout);
        shortEatspanelLayout.setHorizontalGroup(
            shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shortEatspanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shortEatspanelLayout.createSequentialGroup()
                        .addComponent(cupCake, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qCupCake, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shortEatspanelLayout.createSequentialGroup()
                        .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(chickenBurger, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fishBurger, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hotDog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(qFishBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(qHotDog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shortEatspanelLayout.createSequentialGroup()
                        .addComponent(doNut, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qDoNut, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addGroup(shortEatspanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shortEatspanelLayout.setVerticalGroup(
            shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shortEatspanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qCupCake, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cupCake))
                .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(shortEatspanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(doNut)
                        .addGap(34, 34, 34)
                        .addComponent(hotDog)
                        .addGap(47, 47, 47))
                    .addGroup(shortEatspanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(qDoNut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qFishBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fishBurger))
                .addGap(40, 40, 40)
                .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chickenBurger))
                .addGap(48, 48, 48)
                .addGroup(shortEatspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(shortEatspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 450, 500));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Receipt");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 480, 540));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        costOfShortEats.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        costOfShortEats.setForeground(new java.awt.Color(255, 255, 255));
        costOfShortEats.setText("Cost of shorteats");

        costOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        costOfDrinks.setForeground(new java.awt.Color(255, 255, 255));
        costOfDrinks.setText("Cost Of Drinks");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Charge");

        totalCharge.setForeground(new java.awt.Color(255, 255, 255));
        totalCharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        pricecostOfDrinks.setForeground(new java.awt.Color(255, 255, 255));
        pricecostOfDrinks.setText("         ");
        pricecostOfDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        pcostOfShortEats.setForeground(new java.awt.Color(255, 255, 255));
        pcostOfShortEats.setText("          ");
        pcostOfShortEats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(costOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pricecostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costOfShortEats, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pcostOfShortEats, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(costOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(pricecostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(costOfShortEats, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pcostOfShortEats, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 910, 190));

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));

        print.setText("Print");

        total.setText("Total");

        close.setText("Close");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(print)
                .addGap(44, 44, 44)
                .addComponent(reset)
                .addGap(35, 35, 35)
                .addComponent(close)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(close)
                        .addComponent(reset)
                        .addComponent(print)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nesCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nesCafeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nesCafeActionPerformed

    private void iceCofeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iceCofeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iceCofeeActionPerformed

    private void teaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaActionPerformed

    private void doNutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doNutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doNutActionPerformed

    private void hotDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotDogActionPerformed

    private void fishBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishBurgerActionPerformed

    private void cupCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupCakeActionPerformed

    private void cheeseBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheeseBurgerActionPerformed

    private void chickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chickenBurgerActionPerformed

    private void qCupCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qCupCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qCupCakeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       
        pricecostOfDrinks.setText(null);
        costOfDrinks.setText(null);
        costOfShortEats.setText(null);
        pricecostOfDrinks.setText(null);
        pcostOfShortEats.setText(null);
        qCheeseBurger.setText(null);
        qChickenBurger.setText(null);
        qCupCake.setText(null);
        qDoNut.setText(null);
        qFishBurger.setText(null);
        qHotDog.setText(null);
        qIceCofee.setText(null);
        qMilo.setText(null);
        qNesCafe.setText(null);
        qNesTea.setText(null);
        qTea.setText(null);
        qhotcofee.setText(null);
           
                
                
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CafeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CafeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CafeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CafeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CafeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cheeseBurger;
    private javax.swing.JCheckBox chickenBurger;
    private javax.swing.JButton close;
    private javax.swing.JLabel costOfDrinks;
    private javax.swing.JLabel costOfShortEats;
    private javax.swing.JCheckBox cupCake;
    private javax.swing.JCheckBox doNut;
    private javax.swing.JPanel drinkPanel;
    private javax.swing.JCheckBox fishBurger;
    private javax.swing.JCheckBox hotCoffee;
    private javax.swing.JCheckBox hotDog;
    private javax.swing.JCheckBox iceCofee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox milo;
    private javax.swing.JCheckBox nesCafe;
    private javax.swing.JCheckBox nesTea;
    private javax.swing.JLabel pcostOfShortEats;
    private javax.swing.JLabel pricecostOfDrinks;
    private javax.swing.JButton print;
    private javax.swing.JTextField qCheeseBurger;
    private javax.swing.JTextField qChickenBurger;
    private javax.swing.JTextField qCupCake;
    private javax.swing.JTextField qDoNut;
    private javax.swing.JTextField qFishBurger;
    private javax.swing.JTextField qHotDog;
    private javax.swing.JTextField qIceCofee;
    private javax.swing.JTextField qMilo;
    private javax.swing.JTextField qNesCafe;
    private javax.swing.JTextField qNesTea;
    private javax.swing.JTextField qTea;
    private javax.swing.JTextField qhotcofee;
    private javax.swing.JButton reset;
    private javax.swing.JPanel shortEatspanel;
    private javax.swing.JCheckBox tea;
    private javax.swing.JButton total;
    private javax.swing.JLabel totalCharge;
    // End of variables declaration//GEN-END:variables
}
